{
  imports = [
    ./amneziawg.nix
    ./boot.nix
    ./environment.nix
    ./fish.nix
    ./fonts.nix
    ./hardware.nix
    ./i2c.nix
    ./i18n.nix
    ./l2tp-ipsec.nix
    ./networking.nix
    ./nix.nix
    ./security.nix
    ./services.nix
    ./systemd.nix
    ./time.nix
    ./user.nix
  ];
}
